use std::path::{Path, PathBuf};
use std::process::Command;
use std::{env, fs};

fn main() {
    print_git_rerun_paths();

    let commit = Command::new("git")
        .args(["rev-parse", "--short", "HEAD"])
        .output()
        .ok()
        .filter(|output| output.status.success())
        .and_then(|output| String::from_utf8(output.stdout).ok())
        .map(|stdout| stdout.trim().to_string())
        .filter(|commit| !commit.is_empty())
        .unwrap_or_else(|| "unknown".to_string());

    println!("cargo:rustc-env=FLUENT_BUILD_COMMIT={commit}");

    generate_bundled_skills();
}

fn print_git_rerun_paths() {
    for args in [
        ["rev-parse", "--git-path", "HEAD"].as_slice(),
        ["rev-parse", "--git-path", "index"].as_slice(),
    ] {
        if let Some(path) = git_stdout(args) {
            println!("cargo:rerun-if-changed={path}");
        }
    }

    if let Some(head_ref) = git_stdout(["symbolic-ref", "-q", "HEAD"].as_slice())
        && let Some(path) = git_stdout(["rev-parse", "--git-path", &head_ref].as_slice())
    {
        println!("cargo:rerun-if-changed={path}");
    }
}

fn git_stdout(args: &[&str]) -> Option<String> {
    Command::new("git")
        .args(args)
        .output()
        .ok()
        .filter(|output| output.status.success())
        .and_then(|output| String::from_utf8(output.stdout).ok())
        .map(|stdout| stdout.trim().to_string())
        .filter(|stdout| !stdout.is_empty())
}

fn generate_bundled_skills() {
    let skills_dir = PathBuf::from("skills");
    println!("cargo:rerun-if-changed=skills");

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let dest = out_dir.join("bundled_skills.rs");

    let mut entries: Vec<(String, String)> = Vec::new();

    if skills_dir.is_dir() {
        collect_skill_files(&skills_dir, &skills_dir, &mut entries);
    }

    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let mut code = String::new();
    code.push_str("/// Bundled skill files generated by build.rs.\n");
    code.push_str("/// Each entry is (relative_path, file_content).\n");
    code.push_str("pub const BUNDLED_SKILL_FILES: &[(&str, &str)] = &[\n");
    for (rel_path, content) in &entries {
        code.push_str("    (");
        write_rust_str_literal(&mut code, rel_path);
        code.push_str(", ");
        write_rust_str_literal(&mut code, content);
        code.push_str("),\n");
    }
    code.push_str("];\n");

    fs::write(&dest, code).expect("failed to write bundled_skills.rs");
}

fn collect_skill_files(base: &Path, dir: &Path, entries: &mut Vec<(String, String)>) {
    let mut dir_entries: Vec<fs::DirEntry> = fs::read_dir(dir)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", dir.display()))
        .collect::<Result<_, _>>()
        .unwrap_or_else(|e| panic!("failed to iterate {}: {e}", dir.display()));
    dir_entries.sort_by_key(|e| e.file_name());

    for entry in dir_entries {
        let path = entry.path();
        let metadata = fs::metadata(&path).unwrap_or_else(|e| {
            panic!("failed to read metadata for {}: {e}", path.display())
        });

        if metadata.is_dir() {
            collect_skill_files(base, &path, entries);
        } else if metadata.is_file() {
            let rel = path
                .strip_prefix(base)
                .unwrap()
                .to_string_lossy()
                .replace('\\', "/");
            let content = fs::read_to_string(&path).unwrap_or_else(|e| {
                panic!("failed to read {}: {e}", path.display())
            });
            entries.push((rel, content));
        }
    }
}

fn write_rust_str_literal(out: &mut String, s: &str) {
    out.push('"');
    for ch in s.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c => out.push(c),
        }
    }
    out.push('"');
}
